"""face_embeddings: login biometrico Fase A

Revision ID: 8886f5907d3b
Revises: 1ce41988abf4
Create Date: 2026-09-27 05:04:34.783175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types


# revision identifiers, used by Alembic.
revision: str = '8886f5907d3b'
down_revision: Union[str, None] = '1ce41988abf4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('face_embeddings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('embedding', sa.LargeBinary(), nullable=False),
    sa.Column('modelo', sa.String(length=50), nullable=False),
    sa.Column('creado_en', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_face_embeddings_usuario_id'), 'face_embeddings', ['usuario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_face_embeddings_usuario_id'), table_name='face_embeddings')
    op.drop_table('face_embeddings')
    # ### end Alembic commands ###
