"""verificacion_intentos: historial de la Fase A2

Revision ID: b11ca525ba46
Revises: 8886f5907d3b
Create Date: 2026-09-27 15:13:16.907212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import app.database.types


# revision identifiers, used by Alembic.
revision: str = 'b11ca525ba46'
down_revision: Union[str, None] = '8886f5907d3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificacion_intentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dni', sa.String(length=8), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('coincide', sa.Boolean(), nullable=False),
    sa.Column('similitud', sa.Numeric(precision=6, scale=4), nullable=True),
    sa.Column('creado_en', app.database.types.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificacion_intentos')
    # ### end Alembic commands ###
